Repository smwu-aws-cloud-club/courseX-project, pull requests merged in 2025-05, with the labels that each got.

#36 [Feat/#35] authAxios에 로그인 헤더 설정
  course-x-frontend/src/api/course.js
  course-x-frontend/src/axios.js
Labels: 🌱 feat

#34 [Feat/#7] 사용자 로그 조회 API 구현
  courseX-backend/build.gradle.kts
  courseX-backend/src/main/java/com/acc/courseX/config/AsyncConfig.java
  courseX-backend/src/main/java/com/acc/courseX/log/aspect/LogAspect.java
  courseX-backend/src/main/java/com/acc/courseX/log/code/LogSuccess.java
  courseX-backend/src/main/java/com/acc/courseX/log/controller/LogController.java
  courseX-backend/src/main/java/com/acc/courseX/log/dto/LogResponse.java
  courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java
  courseX-backend/src/main/java/com/acc/courseX/log/entity/LogAction.java
  courseX-backend/src/main/java/com/acc/courseX/log/repository/LogRepository.java
  courseX-backend/src/main/java/com/acc/courseX/log/service/LogService.java
  courseX-backend/src/main/java/com/acc/courseX/log/service/LogServiceImpl.java
Labels: 🌱 feat

#39 [Fix/#38]: API 응답 오류 시 기본값을 전달해서 참조 오류 방지
  course-x-frontend/src/api/course.js
  course-x-frontend/src/page/CancelPage.jsx
  course-x-frontend/src/page/EnrollPage.jsx
Labels: 🎈 fix

#43 [Feat/#42] 모니터링 환경 셋팅
  courseX-backend/build.gradle.kts
  courseX-backend/src/main/resources/application-dev.yaml
  courseX-backend/src/main/resources/application-local.yaml
  courseX-backend/src/main/resources/monitoring.yaml
Labels: 🌱 feat

#40 [Feat/#37] main 브랜치에 대한 CD 플로우 구현
  .github/workflows/main-CD.yml
  Docker/docker-compose.yml
  Docker/nginx/conf.d/default.conf
  Docker/nginx/nginx.conf
  Docker/scripts/deploy.sh
  courseX-backend/Dockerfile
Labels: 🌱 feat

#45 [FIX] CD 파이프라인 에러 해결
  .github/workflows/main-CD.yml
Labels: 🎈 fix

#47 [TEST] backend main cd 동작 테스트
  courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java
Labels: 🎫 test

#49 [TEST] backend main cd 동작 테스트 3회차
  courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java
  docker/.DS_Store
  docker/.idea/.gitignore
  docker/.idea/Docker.iml
  docker/.idea/misc.xml
  docker/.idea/modules.xml
  docker/.idea/vcs.xml
  docker/docker-compose.yml
  docker/nginx/conf.d/default.conf
  docker/nginx/nginx.conf
  docker/scripts/deploy.sh
Labels: 🎫 test

#51 [Chore/#50] React Query retry 설정 끄기
  course-x-frontend/src/index.js
Labels: ☂️ chore

#52 [FIX] https 연결
  courseX-backend/src/main/java/com/acc/courseX/log/entity/Log.java
  docker/docker-compose.yml
Labels: 🎈 fix

#55 [Fix/#54]: 엔드포인트에서 /api 제거
  course-x-frontend/src/api/course.js
Labels: 🎈 fix

#67 fix: strip_components를 2로 수정
  .github/workflows/main-CD.yml
  courseX-backend/deploy/scripts/deploy.sh
Labels: 🎈 fix

#69 fix: deploy.sh 파일 위치 수정
  courseX-backend/deploy/deploy.sh
Labels: 🎈 fix

#74 fix: 컨테이너 내부에서 health check를 실행하도록 파일 변경
  courseX-backend/Dockerfile
  courseX-backend/deploy/deploy.sh
Labels: 🎈 fix

#75 fix: 명령어 순서 변경
  courseX-backend/Dockerfile
Labels: 🎈 fix

#77 fix: docker에 no cache 옵션 추가
  .github/workflows/main-CD.yml
  courseX-backend/deploy/deploy.sh
Labels: 🎈 fix

#78 Revert "fix: docker에 no cache 옵션 추가"
  .github/workflows/main-CD.yml
  courseX-backend/deploy/deploy.sh
Labels: 🎈 fix

#81 fix: actuator 변경
  courseX-backend/src/main/resources/application-prod.yaml
Labels: 🎈 fix

#84 fix: jpa.yaml에 prod 추가
  courseX-backend/src/main/resources/jpa.yaml
Labels: 🎈 fix

#85 fix: image tag를 latest로 변경
  .github/workflows/main-CD.yml
  courseX-backend/deploy/deploy.sh
  courseX-backend/deploy/docker-compose.yml
Labels: 🎈 fix

#89 [Fix/#88] deploy.sh에 오류가 발생할 수 있는 명령어에 || true 조건 추가
  courseX-backend/deploy/deploy.sh
Labels: 🎈 fix
